### ISSUE TITLE
提供 filter 暴露函数prop

### ISSUE THREAD

**Issue by ErrorJe** [hql7/wl-tree-transfer#1]
需要自定义filter方法，可以把这个方法暴露出来吗
目前是按照关键字过滤的，现在想要按照特定的过滤算法实现节点过滤

**Comment by hql7** [comment]
稍等-正在路上，cli3版本更新肯滞后，可以先使用https://github.com/hql7/tree-transfer，单文件引入用法与cli3无异

在 2019-12-04 14:21:40，"ErrorJe" <notifications@github.com> 写道：


需要自定义filter方法，可以把这个方法暴露出来吗
目前是按照关键字过滤的，现在想要按照特定的过滤算法实现节点过滤

**Comment by hql7** [comment]
@ErrorJe 已更新

**Comment by ErrorJe** [comment]
> @ErrorJe 已更新

3q

**Comment by ErrorJe** [comment]
3Q
