### ISSUE TITLE
请问下如何直接获取添加后toData中的id,嵌套层次太多了，有没有好的方法直接返回id,不太想遍历toData

### ISSUE THREAD

**Issue by 18317968611** [hql7/wl-tree-transfer#10]
请问下如何直接获取添加后toData中的id,嵌套层次太多了，有没有好的方法直接返回id,不太想遍历toData

**Comment by hql7** [comment]
@18317968611 返回的有

**Comment by 18317968611** [comment]
能详细说下么，我只看到返回的toData是一个嵌套的很多层的菜单数组

**Comment by hql7** [comment]
@18317968611 返回的from、to、和一个{ids，nodes，harfIds，harfNodes}
