### ISSUE TITLE
节点拖拽功能

### ISSUE THREAD

**Issue by ErrorJe** [hql7/wl-tree-transfer#2]
大佬我又来了，现在有2个需求

1 节点拖拽
官方的 tree 可以拖拽，这个组件没有暴露该属性吗？希望可以加上

2 排序问题
就是每次左右拖动后，两侧的最父级节点，可以根据某个字段（可能是 id，也可能是别的）进行排序。因为现在的模式是，节点移动后，是默认放置在最下面的。

**Comment by hql7** [comment]
安排

发自我的iPhone

**Comment by hql7** [comment]
@ErrorJe 可怜人，现在有拖拽了，去el-tree-trensfer
