### ISSUE TITLE
pid是干嘛的

### ISSUE THREAD

**Issue by Cosen95** [hql7/wl-tree-transfer#4]

**Comment by hql7** [comment]
用于穿梭后组装节点时找到父级



在 2020-03-06 10:37:18，"fengshuan" <notifications@github.com> 写道：

**Comment by Jack-cool** [comment]
嗯嗯，已经知道了，就是parentId，多谢解答。
不过，建议文档完善下，:smiley:

**Comment by Jack-cool** [comment]
其实现在，element ui中无论是el-transfer还是el-tree都没有pid属性，这块对于刚开始看的同学来说，会有点懵

**Comment by hql7** [comment]
好建议

发自我的iPhone
