### ISSUE TITLE
当mode是addressList时，右侧的列表能不能改成tree？

### ISSUE THREAD

**Issue by SwordSealCity** [hql7/wl-tree-transfer#5]
当mode是addressList时，右侧的列表能不能改成tree？
功能还是逐条删除

**Comment by hql7** [comment]
瓦特，这个模式是很多人要求穿梭到右侧成list而且左边不减，我才加了这个模式，你这又是特殊要求啊，改了太特殊了

发自我的iPhone

**Comment by SwordSealCity** [comment]
左边还是不减就是右侧是tree，能不能有个参数来控制？

**Comment by hql7** [comment]
我统计一下需求
