### ISSUE TITLE
通讯录模式右侧是否可以初始化？

### ISSUE THREAD

**Issue by DahuaChan** [hql7/wl-tree-transfer#7]
如题目，如果可以该怎么操作，没有的话是否可以开发呢

**Comment by hql7** [comment]
好像是没有，现在项目太多，而且在职，时间严重不足，欢迎大家多多pr，共通为开源做贡献



在 2020-05-06 17:36:14，"Dava" <notifications@github.com> 写道：

如题目，如果可以该怎么操作，没有的话是否可以开发呢

**Comment by hql7** [comment]
有了，忘了通知
